#!/bin/bash

# Align the paired end reads to reference genome
bowtie2 -x ~/project/mapping/bowtie_index/salmonella_typhi -1 ~/project/raw_data/ERR405234_1.fastq -2 ~/project/raw_data/ERR405234_2.fastq -S ~/project/mapping/mapping_2020_02_24/time_24h/mapped_ERR405234.sam

# Convert SAM file to BAM file
samtools view -b -S -o ~/project/mapping/mapping_2020_02_24/time_24h/mapped_ERR405234.bam ~/project/mapping/mapping_2020_02_24/time_24h/mapped_ERR405234.sam

# Sort the BAM file
samtools sort ~/project/mapping/mapping_2020_02_24/time_24h/mapped_ERR405234.bam -o ~/project/mapping/mapping_2020_02_24/time_24h/mapped_ERR405234.sorted.bam

# Index the sorted BAM file
samtools index ~/project/mapping/mapping_2020_02_24/time_24h/mapped_ERR405234.sorted.bam

